export type Supplier = { ID: number; Name: string; Rating: number; Address: string; Status: string; Qualification?: string };
export type Offer = { ID: number; UnitPrice: number; MOQ: number; Freight: string; DeliveryDays: number; StockStatus: string; Supplier: Supplier };
export type Product = { ID: number; Name: string; Brand: string; Model: string; Unit: string; Thumbnail: string; SalesCount: number; Rating: number; Category: { Name: string }; Offers: Offer[] };
export type ApiEnvelope<T> = { code: number; message: string; data: T };
export type TrendPoint = { Price: number; RecordedAt: string };
export type Trend = { range: string; highest: number; lowest: number; average: number; points: TrendPoint[] };
export type PurchaseOrderItem = {
  id: number;
  offer_id: number;
  product_id: number;
  product_name: string;
  brand: string;
  model: string;
  unit: string;
  supplier_id: number;
  supplier_name: string;
  supplier_status: string;
  stock_status: string;
  moq: number;
  quantity: number;
  locked_unit_price: number;
  current_unit_price: number;
  price_difference: number;
  locked_amount: number;
  current_amount: number;
  amount_difference: number;
  delivery_days: number;
  freight: string;
  purchasable: boolean;
  blocked_reason?: string;
};
export type PurchaseOrder = {
  id: number;
  items: PurchaseOrderItem[];
  locked_total: number;
  current_total: number;
  total_difference: number;
  purchasable_count: number;
  unavailable_count: number;
};
