export type Supplier = { ID: number; Name: string; Rating: number; Address: string; Status: string };
export type Offer = { ID: number; UnitPrice: number; MOQ: number; Freight: string; DeliveryDays: number; StockStatus: string; Supplier: Supplier };
export type Product = { ID: number; Name: string; Brand: string; Model: string; Unit: string; Thumbnail: string; SalesCount: number; Rating: number; Category: { Name: string }; Offers: Offer[] };
export type ApiEnvelope<T> = { code: number; message: string; data: T };
export type TrendPoint = { Price: number; RecordedAt: string };
export type Trend = { range: string; highest: number; lowest: number; average: number; points: TrendPoint[] };
export type PurchaseOrderItem = {
  id: number;
  offer_id: number;
  product_id: number;
  product_name: string;
  product_model: string;
  unit: string;
  supplier_id: number;
  supplier_name: string;
  quantity: number;
  moq: number;
  locked_unit_price: number;
  current_price: number;
  price_difference: number;
  stock_status: string;
  supplier_status: string;
  purchasable: boolean;
  reason: string;
};
export type PurchaseOrder = {
  items: PurchaseOrderItem[];
  total_locked_amount: number;
  total_current_amount: number;
  total_difference: number;
  purchasable_count: number;
};
